### PR TITLE
chore: docker 

### PR DESCRIPTION
**Pull request by AliAryanTech**

### CODE REVIEW

**Comment by AliAryanTech** [comment]
just clean docker

**Comment by SpyAJ3** [comment]
Please let the qrcode be visible in on your profile

**Comment by AliAryanTech** [comment]
@FantoX001 merge it bruh

**Comment by FantoX001** [comment]
> Please let the qrcode be visible in on your profile

Web QR integration code added to provide extra security to prevent your WhatsApp account from hacking. So as an extra layer of Privacy and Security the web integration added. And it's better that 3rd Party QR scanning systems where Either you have to upload the session file on GitHub or properly copy paste the session ID. But here you can use any Session ID string.

**Pull request merged**
